let dessin = [
  "squelette",
  "visage",
  "baleine",
  "anatomie",
  "phoque",
  "méduse",
  "seiche",
  "axoloto",
  "tortue",
  "pikachu",
  "poulpe",
  "crabe",
  "coquillage",
  "requin",
  "sirène",
  "piaf",
  "carapuce",
  "lion",
  "éléphant",
  "léboulérou",
  "pingouin",
  "brocélôme",
  "koala",
  "panda",
  "métalosse",
  "hibou",
  "lapin",
  "biche",
  "vache",
  "souris",
  "cochon",
  "renard",
  "mouton",
  "chien",
  "emote",
  "chat",
  "radio",
  "table",
  "thé",
  "outils",
  "éléctroménager",
  "montgolfière",
  "arc-en-ciel",
  "forêt",
  "montagne",
  "maquillage",
  "téléphone",
  "tasse",
  "palette",
  "lit",
  "balais",
  "cactus",
  "fleurs",
  "surf",
  "maillot de bain",
  "arrosoir",
  "sapin",
  "avion",
  "sac à dos",
  "étoile de mer",
  "chaussette",
  "valise",
  "lunettes de soleil",
  "citrouille",
  "château de sable",
  "bonhomme de neige",
  "vampire",
  "sorcière",
  "mage",
  "feuille",
  "ballon en mouvement",
  "calcifer",
  "abeille",
  "fleur en pot",
  "pirate",
  "fusée",
  "vaisseau spatial",
  "licorne",
  "lampe du génie",
  "gentil monstre",
  "dragon",
  "fée",
  "génie",
  "fantôme",
  "maison hantée",
  "poisson",
  "girafe",
  "poule",
  "ours en peluche",
  "sandwich",
  "tartine",
  "taco",
  "brique de lait",
  "ananas",
  "pizza",
  "popcorn",
  "glace",
  "tomate",
  "piment",
  "aubergine",
  "poivron",
  "petit pois",
  "ramen",
  "muffin",
  "milkshake",
  "burger",
  "hotdog",
  "poire",
  "pomme",
  "avocat",
  "fraise",
  "orange",
  "pastèque",
  "donut",
  "bubble tea",
  "frites",
  "wrap",
  "gâteau d'anniversaire",
  "maïs",
  "emotes cheveux courts",
  "emote cheveux attachés",
  "emote cheveux longs",
];

let bouton = document.querySelector("#randomize");
let resultat = document.querySelector("#drawingresult");
bouton.addEventListener("click", function () {
  let numrandom = Math.floor(Math.random() * dessin.length);
  resultat.textContent = dessin[numrandom];
});
